### ISSUE TITLE
credits to license

### ISSUE THREAD

**Issue by RodrigueLemaire** [mbblp/mod-poketest#1]
you should rename credits to license for a better comprehension :+1:

**Comment by lnjX** [comment]
And add a license at all! Without a license no one knows if he/she can use/redistribute/copy/whatever it. If  you want to make them public domain or something as this, take CC0 1.0. If you still want to be credited maybe MIT. Or maybe LGPLv2.1+ (most restrictive).

**Comment by Desour** [comment]
~~Isn't the code from Blockmen's mod?~~

For the media you can eg. take CC BY-SA 3.0.

https://creativecommons.org/licenses/by-sa/3.0/
https://creativecommons.org/publicdomain/zero/1.0/

**Comment by lnjX** [comment]
@DS-Minetest Yes, you're right the media's license should be better CC BY-SA 3.0 / CC0 (not LGPL/MIT).

@mbblp You shouldn't add the engine's licenses in the header of your files. - That doesn't make any sense.

**Comment by mbruchert** [comment]
OK i will delete it

**Comment by mbruchert** [comment]
I think i edit it right so i will close this !
