### ISSUE TITLE
don't use a modpack for different pokemons

### ISSUE THREAD

**Issue by Desour** [mbblp/mod-poketest#2]
Make instead different files, like `pikachu.lua` and use `dofile` in `init.lua`.
If you want to make them deactivatable use settings instead.
For more information, just ask.

**Comment by lnjX** [comment]
No this is ok and good. I don't see any problem here. This way other mods can depend only on specific pokemons. If you need any functions in all mods, you can add another pokemon helper mod to the pack, that adds it. All pokemon mods that use them have to depend on the pokemon helper mod.

**Comment by Desour** [comment]
I don't think, any mod will depend on a specific pokemon.

**Comment by lnjX** [comment]
@DS-Minetest I also don't really think so, but why not?! Why shouldn't you put every file into its own mod into a modpack? I don't see any disadvantage. (I also don't like it to have a messed up mod structure: several lua files in between READMEs, depends.txt, description.txt, mod.conf, etc.).

**Comment by Desour** [comment]
> (I also don't like it to have a messed up mod structure: several lua files in between READMEs, depends.txt, description.txt, mod.conf, etc.).

You can put the files into folders eg. `dofile(path.."/electros/pikatschuh")`.

Modpacks can not be as good structured as files structures.

To see the difference between modpacks which are only thought as one mod and mods with file structures, compare mesecons and technic.

Also if a new pokemon is added, the user has to activate it again.

I don't see any advantage of a modpack here.
Modpacks make no sense if every mod in it is always used by everyone.

But it's all decided by @mbblp.

**Comment by lnjX** [comment]
> Also if a new pokemon is added, the user has to activate it again.

Oh, I didn't know that. Then I can understand you.
